---
- name: Install and configure Nginx
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

- name: Deploy repo to web server
  hosts: web
  become: yes
  vars:
    web_root: /var/www/html
  tasks:
    - name: Clone repo from GitHub
      git:
        repo: "https://github.com/okekolawolesunday009/DevOps-Stage-6"
        dest: /tmp/mini_finance
        version: main

    - name: Copy site to web root
      copy:
        src: /tmp/mini_finance/
        dest: "{{ web_root }}/"
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- name: Verify Web Deployment
  hosts: localhost
  tasks:
    - name: Fetch homepage from remote web server
      uri:
        url: "http://{{ groups['web'][0] }}"
        return_content: yes
      register: site_check

    - name: Print website response
      debug:
        msg: "{{ site_check.content | truncate(200) }}"
